[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
dependencies = [
#    "altgraph",
#    "certifi",
#    "charset-normalizer",
    "distro",
#    "idna",
    "packaging",
    "psutil",
    "pythondialog",
    "requests",
    "inotify", # Required for watching when the auto-update setting changes
#    "tkinter",  # actually provided by a system package, not a python package
#    "urllib3",
]
name = "matheteusate"
dynamic = ["readme", "version"]
requires-python = ">=3.12"

[project.optional-dependencies]
build = ["pyinstaller"]

[project.scripts]
matheteusate = "matheteusate.main:main"

[tool.setuptools.dynamic]
readme = {file = ["README.md"], content-type = "text/plain"}
version = {attr = "matheteusate.constants.LLI_CURRENT_VERSION"}

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
"matheteusate.img" = ["*icon.png"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F"]

[tool.mypy]
warn_unreachable = true
disallow_untyped_defs = false
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
no_implicit_reexport = true
extra_checks = true
check_untyped_defs = true

[[tool.mypy.overrides]]
module = "matheteusate.config"
disallow_untyped_calls = true

disallow_any_generic = false
strict_equality = true
